# Generated by Django 5.2.8 on 2026-01-20 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockhistory',
            old_name='date',
            new_name='timestamp',
        ),
    ]
