# Generated by Django 5.2.8 on 2026-01-24 18:27

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_product_unique_product_per_category'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_product_per_category',
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('category'), name='unique_product_per_category_ci'),
        ),
    ]
